// A simple mapping of search terms to related product categories or keywords
// This can be expanded or made more sophisticated in the future.
export const recommendationMapping: { [key: string]: string[] } = {
  "toothpaste": ["toothbrush", "mouthwash", "dental floss", "toilet tissue", "electric toothbrush heads", "water flosser tips", "tongue scraper"],
  "shampoo": ["conditioner", "body lotion", "soap", "hair brush", "towel"],
  "spoon": ["plate", "bowl", "fork", "knife", "napkin"],
  "coffee": ["coffee maker", "coffee beans", "sugar", "milk", "mug", "thermos"],
  "tea": ["tea pot", "tea bags", "honey", "lemon", "cup", "tea kettle"],
  "milk": ["cereal", "cookies", "bread", "yogurt"],
  "bread": ["butter", "jam", "cheese", "ham"],
  "laptop": ["mouse", "keyboard", "monitor", "headphones", "laptop bag", "charger"],
  "phone": ["charger", "phone case", "earbuds", "screen protector", "smartwatch", "bluetooth speaker", "earphones"],
  "book": ["bookmark", "notebook", "pen", "magazine"],
  "shirt": ["pants", "shorts", "jacket", "socks"],
  "shoes": ["socks", "shoe polish", "shoe laces"],
  "detergent": ["fabric softener", "laundry basket", "clothesline", "dishwasher pods", "laundry detergent"],
  "battery": ["flashlight", "remote control", "toys", "battery charger", "headlamp"],
  "water": ["water bottle", "juice", "soda"],
  "snack": ["chips", "candy", "cookies", "juice"],
  "toy": ["game", "puzzle", "doll", "action figure"],
  "pen": ["notebook", "pencil", "eraser"],
  "paper": ["printer", "stapler", "folder", "shredder"],
  "chair": ["table", "desk", "lamp"],
  "bed": ["pillow", "blanket", "sheets"],
  "tv": ["remote control", "speakers", "hdmi cable", "movie"],
  "camera": ["sd card", "camera bag", "tripod", "camera lens", "drone"],
  "headphones": ["mp3 player", "phone", "laptop", "speaker"],
  "keyboard": ["mouse", "monitor", "computer", "gaming keyboard"],
  "mouse": ["keyboard", "mouse pad", "computer", "gaming mouse"],
  "monitor": ["keyboard", "mouse", "computer", "monitor stand"],
  "printer": ["ink", "paper", "scanner", "printer ink"],
  "router": ["ethernet cable", "modem"],
  "speaker": ["amplifier", "microphone", "headphones", "bluetooth speaker"],
  "microphone": ["speaker", "audio interface", "webcam"],
  "guitar": ["guitar strings", "guitar pick", "amplifier"],
  "drum": ["drum sticks", "cymbals"],
  "paint": ["paint brush", "canvas", "easel", "art supplies", "paint set"],
  "brush": ["paint", "comb"],
  "canvas": ["paint", "easel", "art easel", "paint by number", "art canvas set"],
  "easel": ["paint", "canvas", "art easel"],
  "flower": ["vase", "pot", "soil"],
  "plant": ["pot", "soil", "watering can"],
  "pot": ["plant", "soil", "flower", "plant pot"],
  "soil": ["plant pot", "plant", "pot", "flower", "fertilizer", "seed", "seed packets", "flower seeds", "vegetable seeds"],
  "watering can": ["plant", "flower"],
  "fertilizer": ["plant", "soil", "plant food", "plant food spikes"],
  "seed": ["soil", "plant"],
  "tool": ["toolbox", "hammer", "screwdriver"],
  "hammer": ["nails", "toolbox"],
  "screwdriver": ["screws", "toolbox"],
  "nails": ["hammer"],
  "screws": ["screwdriver"],
  "light bulb": ["lamp", "flashlight", "ladder", "smart light bulb"],
  "lamp": ["light bulb", "desk", "desk lamp"],
  "battery charger": ["battery"],
  "umbrella": ["raincoat", "rain boots", "patio furniture", "beach umbrella"],
  "sunglasses": ["hat", "sunscreen"],
  "wallet": ["keys", "phone"],
  "bag": ["wallet", "keys", "phone"],
  "watch": ["battery"],
  "jewelry": ["jewelry box"],
  "perfume": ["lotion", "deodorant", "perfume travel size"],
  "candle": ["lighter", "housewarming gift"],
  "soap": ["shampoo", "conditioner", "body wash"],
  "towel": ["soap", "shampoo", "beach bag", "swimsuit", "beach towel"],
  "mirror": ["comb", "tweezers"],
  "comb": ["brush", "mirror", "hair brush", "beard comb"],
  "hair dryer": ["hair brush"],
  "razor": ["shaving cream", "razor blades"],
  "shaving cream": ["aftershave", "razor", "beard trimmer", "electric shaver"],
  "deodorant": ["perfume"],
  "lotion": ["soap", "perfume", "body wash", "body scrub", "hand soap"],
  "sunscreen": ["hat", "sunglasses", "insect repellent", "after-sun lotion", "sunscreen stick"],
  "first aid kit": ["bandages", "antiseptic", "pain reliever", "thermometer", "emergency blanket", "first aid manual", "first aid ointment"],
  "bandages": ["first aid kit", "antiseptic wipes"],
  "antiseptic": ["bandages", "first aid kit"],
  "pain reliever": ["first aid kit", "fever reducer"],
  "vitamins": ["supplements", "vitamins for kids", "vitamins organizer"],
  "protein powder": ["creatine", "shaker bottle", "protein bars", "protein shaker", "pre-workout"],
  "yoga mat": ["yoga block", "resistance bands", "yoga mat cleaner", "yoga wheel", "pilates ring", "exercise ball", "yoga mat bag"],
  "dumbbell": ["weights", "dumbbell set", "dumbbell rack"],
  "treadmill": ["running shoes", "elliptical", "stationary bike", "treadmill lubricant"],
  "elliptical": ["treadmill", "rowing machine"],
  "stationary bike": ["treadmill"],
  "bicycle": ["helmet", "bike pump", "bicycle helmet", "bike light", "bike repair kit"],
  "helmet": ["bicycle", "bicycle helmet"],
  "bike pump": ["bicycle"],
  "tent": ["sleeping bag", "camping stove", "camping tent", "camping hammock"],
  "camping stove": ["tent", "camping cookware", "camping lantern", "camping stove fuel"],
  "backpack": ["water bottle", "lunch box", "hiking boots", "backpacking backpack"],
  "map": ["compass", "gps device"],
  "compass": ["map", "binoculars"],
  "fishing rod": ["fishing reel", "fishing lure", "fishing line", "fishing tackle box", "fishing net", "fishing waders"],
  "fishing lure": ["fishing rod", "fishing line"],
  "fishing line": ["fishing rod", "fishing lure"],
  "grill": ["charcoal", "bbq tools", "propane tank", "grill brush", "grill cover"],
  "charcoal": ["grill"],
  "bbq tools": ["grill", "father's day decorations"],
  "cooler": ["ice", "ice pack", "cooler bag", "cooler with wheels", "portable cooler"],
  "ice": ["cooler"],
  "pool": ["swimsuit", "goggles"],
  "swimsuit": ["towel", "goggles", "pool float"],
  "goggles": ["swimsuit", "flippers", "swim goggles", "swim kickboard"],
  "board game": ["card game", "puzzle", "board game expansion", "board game organizer", "board game sleeves"],
  "puzzle": ["board game", "puzzle book", "puzzle mat", "puzzle glue", "puzzle sorter"],
  "art supplies": ["paint", "brushes"],
  "craft supplies": ["glue", "scissors", "craft kit", "craft organizer"],
  "sewing machine": ["fabric", "thread", "sewing machine needles"],
  "fabric": ["thread", "sewing machine", "sewing patterns", "fabric scissors", "zippers"],
  "thread": ["fabric", "sewing machine", "needles"],
  "glue": ["scissors", "craft supplies", "craft glue"],
  "scissors": ["glue", "craft supplies", "craft paper", "craft kit"],
  "gift wrap": ["ribbon", "gift bag", "gift tag", "wrapping paper", "gift wrap cutter", "gift wrap organizer"],
  "ribbon": ["gift wrap", "bow", "gift basket"],
  "gift bag": ["gift wrap", "gift card", "gift bag assortment", "gift bag tissue paper"],
  "card": ["envelope", "greeting card"],
  "envelope": ["card", "greeting card", "stamp"],
  "stamp": ["envelope"],
  "pen drive": ["hard drive"],
  "hard drive": ["pen drive", "external hard drive"],
  "modem": ["router"],
  "screen": ["projector", "projector screen"],
  "remote control": ["battery"],
  "charger": ["phone", "laptop", "adapter", "charging cable"],
  "adapter": ["charger"],
  "cable": ["charger", "adapter"],
  "earphones": ["phone", "earbuds"],
  "cleaning supplies": ["gloves", "cleaning caddy"],
  "gloves": ["scarf", "cleaning supplies", "gardening gloves"],
  "sponge": ["dish soap"],
  "dish soap": ["sponge", "dish brush"],
  "trash can": ["trash bags", "kitchen trash can", "recycling bin"],
  "trash bags": ["trash can", "trash can liners"],
  "paper towels": ["toilet paper", "paper towel holder"],
  "toilet paper": ["paper towels", "tissue box", "toilet brush"],
  "tissue box": ["toilet paper"],
  "hand soap": ["lotion", "hand sanitizer", "hand soap dispenser"],
  "conditioner": ["shampoo"],
  "body wash": ["lotion"],
  "face wash": ["moisturizer", "face toner"],
  "moisturizer": ["face wash", "serum"],
  "after-sun lotion": ["sunscreen"],
  "makeup": ["makeup remover", "makeup kit", "makeup brushes", "makeup sponge"],
  "makeup remover": ["makeup"],
  "hair spray": ["hair gel", "hair styling tools"],
  "hair gel": ["hair spray", "hair gel for men"],
  "hair brush": ["comb", "hair dryer"],
  "toothbrush": ["toothpaste", "electric toothbrush"],
  "mouthwash": ["toothpaste", "tongue cleaner"],
  "dental floss": ["toothpaste", "water flosser"],
  "electric toothbrush": ["toothbrush heads", "electric toothbrush charger"],
  "toothbrush heads": ["electric toothbrush"],
  "aftershave": ["shaving cream", "aftershave balm"],
  "razor blades": ["razor"],
  "nail clippers": ["nail file", "nail clipper set"],
  "nail file": ["nail clippers"],
  "tweezers": ["mirror", "nail clipper set"],
  "cotton swabs": ["cotton balls"],
  "cotton balls": ["cotton swabs", "cotton pads"],
  "antiseptic wipes": ["bandages"],
  "fever reducer": ["pain reliever"],
  "thermometer": ["first aid kit", "blood pressure monitor"],
  "supplements": ["vitamins"],
  "creatine": ["protein powder"],
  "pre-workout": ["protein powder"],
  "resistance bands": ["yoga mat", "resistance loop bands", "resistance bands set", "pull-up assist bands"],
  "resistance bands set": ["jump rope", "exercise mat", "resistance band set with handles"],
  "yoga block": ["yoga mat", "yoga strap"],
  "yoga strap": ["yoga block"],
  "pilates ring": ["yoga mat"],
  "exercise ball": ["yoga mat"],
  "weight bench": ["dumbbells", "weight lifting belt"],
  "dumbbell set": ["kettlebell", "dumbbell rack"],
  "kettlebell": ["dumbbell set", "kettlebell set"],
  "barbell collars": ["barbell"],
  "pull-up assist bands": ["pull-up bar"],
  "boxing hand wraps": ["boxing gloves"],
  "basketball net": ["basketball hoop"],
  "soccer goal": ["soccer ball"],
  "baseball batting tee": ["baseball bat"],
  "tennis ball machine": ["tennis racket"],
  "golf ball retriever": ["golf balls"],
  "ski boot bag": ["ski boots"],
  "snowboard bag": ["snowboard"],
  "camping hammock": ["tent"],
  "camping table with storage": ["camping table"],
  "portable cooler": ["ice packs"],
  "beach tent": ["beach blanket"],
  "swim goggles anti-fog spray": ["swim goggles"],
  "pool skimmer": ["pool chemicals"],
  "board game sleeves": ["board game"],
  "card game playmat": ["card game"],
  "puzzle sorter": ["puzzle"],
  "art canvas set": ["paint set"],
  "craft organizer": ["craft supplies"],
  "sewing machine needles": ["sewing machine"],
  "yarn bowl": ["yarn"],
  "crochet hook set": ["crochet hooks"],
  "embroidery kit for beginners": ["embroidery hoop"],
  "jewelry making pliers set": ["jewelry making kit"],
  "candle wax warmer": ["candle wax"],
  "soap making molds": ["soap base"],
  "gift wrap cutter": ["wrapping paper"],
  "gift bag tissue paper": ["gift bags"],
  "party banner": ["balloons"],
  "party favors": ["party bags"],
  "party bags": ["party favors"],
  "birthday candles": ["birthday cake"],
  "halloween costume": ["halloween mask"],
  "christmas decorations": ["christmas lights", "christmas tree"],
  "easter eggs": ["easter basket"],
  "valentine's day card": ["chocolate box"],
  "mother's day gift": ["flower vase"],
  "father's day gift": ["grill tools"],
  "graduation gift": ["diploma frame"],
  "wedding gift": ["toaster"],
  "baby shower gift": ["baby clothes"],
  "newborn gift": ["baby blanket"],
  "housewarming gift": ["candle"],
  "thank you card": ["gift card"],
  "get well soon card": ["flowers"],
  "sympathy card": ["flowers"],
  "anniversary card": ["chocolate box"],
  "congratulations card": ["balloons"],
  "good luck card": ["four leaf clover"],
  "sorry card": ["flowers"],
  "thinking of you card": ["flowers"],
  "just because card": ["flowers"],
  "love card": ["chocolate box"],
  "friendship card": ["coffee mug"],
  "teacher appreciation card": ["gift card"],
  "boss's day card": ["gift card"],
  "secretary's day card": ["gift card"],
  "administrative professionals day card": ["gift card"],
  "veterans day card": ["american flag"],
  "memorial day card": ["american flag"],
  "fourth of july decorations": ["fourth of july banner", "american flag"],
};